application: mathquizer-1306
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/bootstrap/css

- url: /fonts
  static_dir: static/fonts

- url: /partials
  static_dir: static/partials


# Add announcement using memcache.
- url: /crons/set_announcement
  script: main.app
  login: admin

# Add email confirmation using task queue. Used in when creating new conference.
- url: /tasks/send_confirmation_email
  script: main.app
  login: admin

# Add email confirmation using task queue. Used in when creating new session.
- url: /tasks/send_confirmation_email2
  script: main.app
  login: admin

# Add set featured speaker using task queue.
- url: /tasks/set_featured_speaker
  script: main.app
  login: admin

- url: /_ah/spi/.*
  script: conference.api
  secure: always

libraries:

- name: webapp2
  version: latest

- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest

builtins:

# Enables Google AppStats
- appstats: on